# Generated by Django 3.1.7 on 2021-03-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Menu')),
                ('slug', models.SlugField(default='slug', unique=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa usługi')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł strony')),
                ('slug', models.SlugField(default='slug', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='website.category')),
            ],
            options={
                'verbose_name': 'Usługi',
                'verbose_name_plural': 'Usługi',
            },
        ),
    ]
