# Generated by Django 3.1.7 on 2021-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_car_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Obraz podglądu')),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Obraz artykułu')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa artykułu')),
                ('short_desc', models.TextField(max_length=300, verbose_name='Krótki opis')),
                ('full_desc', models.TextField(verbose_name='Zawartosć artykułu')),
                ('date', models.DateField(verbose_name='Data')),
                ('slug', models.SlugField(default='slug')),
            ],
            options={
                'verbose_name': 'Wpis',
                'verbose_name_plural': 'Wpisy',
            },
        ),
    ]
