# Generated by Django 3.1.7 on 2021-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_desc',
            field=models.TextField(max_length=700, verbose_name='Krótki opis'),
        ),
    ]
