# Generated by Django 3.1.7 on 2021-03-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210312_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug',
            new_name='slug_service',
        ),
    ]
