# Generated by Django 3.1.7 on 2021-03-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210312_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='slug',
            new_name='slug_car',
        ),
    ]
