# Generated by Django 3.1.7 on 2021-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210312_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='options_car',
            field=models.ManyToManyField(to='website.Option'),
        ),
    ]
