# Generated by Django 3.1.7 on 2021-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_car_options_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Opis samochodu'),
        ),
        migrations.AddField(
            model_name='car',
            name='important_information',
            field=models.TextField(blank=True, null=True, verbose_name='Ważne informacje'),
        ),
    ]
