# Generated by Django 3.1.7 on 2021-03-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210312_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Zdjecie samochodu', null=True, upload_to='slider_images', verbose_name='Zdjecie samochodu')),
                ('slider_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.car')),
            ],
            options={
                'verbose_name': 'Sdjęcie samochodu',
                'verbose_name_plural': 'Sdjęcia samochodu',
            },
        ),
    ]
