# Generated by Django 3.1.7 on 2021-03-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sliderimage_image_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='image_main',
        ),
    ]
