# Generated by Django 3.1.7 on 2021-03-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_servicecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='website.car'),
        ),
    ]
