# Generated by Django 3.1.7 on 2021-03-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210315_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='car',
        ),
    ]
