# Generated by Django 3.1.7 on 2021-03-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210315_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='slider_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='website.car'),
        ),
    ]
