# Generated by Django 3.1.7 on 2021-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_servicecontent_choise'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Ikona'),
        ),
    ]
