# Generated by Django 3.1.7 on 2021-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20210323_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bail',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kaucja'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_day_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 1-3 dni'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_day_15',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 15+ dni'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_day_4',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 4-7 dni'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_day_8',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 8-14 dni'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_day_month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę miesiąc'),
        ),
    ]
