# Generated by Django 3.1.7 on 2021-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210323_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['my_order'], 'verbose_name': 'Usługi', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
        migrations.AddField(
            model_name='option',
            name='images',
            field=models.ImageField(default='img', upload_to='option_icons', verbose_name='Ikona'),
        ),
    ]
