# Generated by Django 3.1.7 on 2021-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20210324_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='images',
        ),
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.CharField(max_length=200, null=True, verbose_name='Ikona'),
        ),
    ]
