# Generated by Django 3.1.7 on 2021-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20210324_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(default='img', upload_to='option email', verbose_name='Ikona'),
        ),
    ]
