# Generated by Django 3.1.7 on 2021-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_mainslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Slider(Strona główna)', 'verbose_name_plural': 'Slider(Strona główna)'},
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_1',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tekst pierwszego przycisku'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tekst drugiego przycisku'),
        ),
    ]
