# Generated by Django 3.1.7 on 2021-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20210325_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='slug_1',
            field=models.CharField(blank=True, help_text='np.: "o-nas"', max_length=500, verbose_name='Link pierwszego przycisku'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slug_2',
            field=models.CharField(blank=True, help_text='np.: "o-nas"', max_length=500, verbose_name='Link drugiego przycisku'),
        ),
    ]
