# Generated by Django 3.1.7 on 2021-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20210325_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='slug_2',
            field=models.CharField(blank=True, help_text='np.: "+48111222333"', max_length=500, verbose_name='Tel drugiego przycisku'),
        ),
    ]
