# Generated by Django 3.1.7 on 2021-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20210330_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_reservation',
            name='choise',
            field=models.CharField(choices=[('Zawarte w cenie', 'Zawarte w cenie'), ('Dodatkowa cena', 'Dodatkowa cena')], default='Dodatkowa cena', max_length=100, verbose_name='Rodzaj ceny'),
        ),
        migrations.AlterField(
            model_name='option_reservation',
            name='choise_price',
            field=models.CharField(choices=[('Cena za dobę', 'Cena za dobę'), ('Cena pojedyncza', 'Cena pojedyncza')], default='Cena za dobę', max_length=100, verbose_name='Naliczanie ceny'),
        ),
    ]
