# Generated by Django 3.1.7 on 2021-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20210410_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Porządek'),
        ),
    ]
