# Generated by Django 3.1.7 on 2021-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_car_show_on_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['my_order'], 'verbose_name': 'Samochód', 'verbose_name_plural': 'Samochody'},
        ),
        migrations.AddField(
            model_name='mainslider',
            name='link_1',
            field=models.CharField(blank=True, max_length=800, verbose_name='Link pierwszego przycisku'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='link_2',
            field=models.CharField(blank=True, max_length=800, verbose_name='Link drugiego przycisku'),
        ),
        migrations.AlterField(
            model_name='car',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Wyświetlić na stronie głównej'),
        ),
    ]
