# Generated by Django 3.1.7 on 2021-04-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20210422_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(help_text='Wprowadź model pojazdu który będzie wyświetlony nad tabelą', max_length=500, verbose_name='Model pojazdu')),
            ],
            options={
                'verbose_name': 'Strona usługi',
                'verbose_name_plural': 'Strona usług',
            },
        ),
    ]
