# Generated by Django 3.1.7 on 2021-04-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20210423_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Wiersz tabeli', 'verbose_name_plural': 'Wiersze tabeli'},
        ),
    ]
