# Generated by Django 3.1.7 on 2021-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20210423_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Tabele strony usług', 'verbose_name_plural': 'Tabele strony usług'},
        ),
        migrations.AlterModelOptions(
            name='servicetable',
            options={'verbose_name': 'Wiersz tabeli', 'verbose_name_plural': 'Wiersze tabeli'},
        ),
    ]
