# Generated by Django 3.1.7 on 2021-04-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20210423_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetable',
            name='servicepage',
        ),
        migrations.AddField(
            model_name='servicetable',
            name='servicetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicetable', to='website.servicepage'),
            preserve_default=False,
        ),
    ]
