# Generated by Django 3.1.7 on 2021-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecontent',
            name='service_content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slider_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug_service',
        ),
        migrations.AddField(
            model_name='service',
            name='choise',
            field=models.CharField(choices=[('Zdjęcie po lewej', 'Zdjęcie po lewej'), ('Zdjęcie po prawej', 'Zdjęcie po prawej')], default='Zdjęcie po lewej', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Zawartość bloku'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Wybierz zdjęcie', null=True, upload_to='service_images', verbose_name='Zdjecie bloku'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Tytuł bloku'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ServiceContent',
        ),
    ]
