# Generated by Django 3.1.7 on 2021-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_auto_20210430_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kolumna')),
                ('desc', models.CharField(max_length=500, verbose_name='Text kolumny')),
            ],
            options={
                'verbose_name': 'Dodatkowa tabela',
                'verbose_name_plural': 'Dodatkowe tabele',
            },
        ),
    ]
