# Generated by Django 3.0.8 on 2021-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_auto_20210518_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_day_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 1-2 dni'),
        ),
    ]
