# Generated by Django 3.0.8 on 2021-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20210707_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_day_4',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za dobę 3-7 dni'),
        ),
    ]
