# Generated by Django 3.1.7 on 2021-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20210723_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_reservation',
            name='option_desc',
            field=models.CharField(max_length=1000, null=True, verbose_name='Opis opcji'),
        ),
        migrations.AlterField(
            model_name='option_reservation',
            name='option_price',
            field=models.CharField(max_length=50, null=True, verbose_name='Cena opcji'),
        ),
    ]
