# Generated by Django 3.1.7 on 2021-07-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_auto_20210723_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraoptions',
            name='desc',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Opis opcji'),
        ),
    ]
