# Generated by Django 3.1.7 on 2021-07-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_auto_20210723_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraoptions',
            name='samochod',
        ),
    ]
