# Generated by Django 3.1.7 on 2021-07-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_remove_extraoptions_samochod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraOptions',
        ),
    ]
