# Generated by Django 3.1.7 on 2021-07-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_delete_extraoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Opcja')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cena')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Opis opcji')),
                ('choise', models.CharField(choices=[('W cenie', 'W cenie'), ('Dodatkowa cena', 'Dodatkowa cena')], default='Dodatkowa cena', max_length=100, verbose_name='Rodzaj ceny')),
                ('choise_price', models.CharField(choices=[('Cena za dobę', 'Cena za dobę'), ('Cena pojedyncza', 'Cena pojedyncza')], default='Cena za dobę', max_length=100, verbose_name='Naliczanie ceny')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_key', to='website.car')),
            ],
            options={
                'verbose_name': 'Opcja dodatkowa',
                'verbose_name_plural': 'Opcje dodatkowe',
            },
        ),
    ]
