# Generated by Django 3.0.8 on 2021-07-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_auto_20210724_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='slug_car',
            new_name='slug_car',
        ),
    ]
