# Generated by Django 3.0.8 on 2021-07-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_auto_20210724_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option_Reservation',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='bail',
            new_name='deposit',
        ),
    ]
