# Generated by Django 3.0.8 on 2021-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_auto_20210730_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='deposit_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kaucja przy odbiorze'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_deposit_2',
            field=models.BooleanField(default=False, verbose_name='Kaucja przy odbiorze?'),
        ),
    ]
