# Generated by Django 3.0.8 on 2021-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_auto_20210730_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_deposit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kaucja przy opłacie kartą'),
        ),
    ]
