# Generated by Django 3.0.8 on 2021-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_auto_20210805_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='Okres')),
            ],
        ),
        migrations.CreateModel(
            name='CarRentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50, verbose_name='Cena za okres')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='website.Car')),
                ('period', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='website.RentPeriod')),
            ],
        ),
    ]
