# Generated by Django 3.0.8 on 2021-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_carrentperiod_rentperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentperiod',
            options={'verbose_name': 'Okres wynajmu', 'verbose_name_plural': 'Okres wynajmu'},
        ),
        migrations.AlterField(
            model_name='carrentperiod',
            name='price',
            field=models.IntegerField(verbose_name='Cena za okres'),
        ),
    ]
