# Generated by Django 3.0.8 on 2021-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_auto_20210809_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentperiod',
            name='text',
            field=models.TextField(default=0, max_length=50, verbose_name='Tekst po liczbie'),
            preserve_default=False,
        ),
    ]
