# Generated by Django 3.0.8 on 2021-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_carrentperiod_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentperiod',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Tekst po liczbie'),
        ),
    ]
