# Generated by Django 3.0.8 on 2021-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_auto_20210809_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentperiod',
            name='price_per_month',
            field=models.BooleanField(default=False, verbose_name='Cena za miesiąc?'),
        ),
        migrations.AlterField(
            model_name='carrentperiod',
            name='price',
            field=models.IntegerField(verbose_name='Cena'),
        ),
    ]
