# Generated by Django 3.0.8 on 2021-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_auto_20210809_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_day_month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cena za miesiąc'),
        ),
    ]
