# Generated by Django 3.0.8 on 2021-08-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_auto_20210810_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_day_1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_day_15',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_day_4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_day_8',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_day_month',
        ),
    ]
