# Generated by Django 3.0.8 on 2021-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_auto_20210810_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='limit_per_day',
            field=models.CharField(default='200 km', max_length=10, verbose_name='Limit dziennie'),
        ),
        migrations.AddField(
            model_name='car',
            name='limit_per_month',
            field=models.CharField(default='3 000 km', max_length=10, verbose_name='Limit miesięcznie'),
        ),
        migrations.AddField(
            model_name='car',
            name='limit_per_year',
            field=models.CharField(default='30 000 km', max_length=10, verbose_name='Limit rocznie'),
        ),
    ]
