# Generated by Django 3.0.8 on 2021-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_auto_20210820_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='month_price',
            field=models.IntegerField(default=0, verbose_name='Cena (miesięcznie)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='Cena za wynajem (dziennie)'),
        ),
    ]
