# Generated by Django 3.0.8 on 2021-08-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_auto_20210820_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrentperiod',
            name='price_per_month',
        ),
    ]
