# Generated by Django 3.0.8 on 2021-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_remove_carrentperiod_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do podstrony'),
        ),
    ]
