# Generated by Django 3.0.8 on 2021-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='promotion',
            field=models.IntegerField(blank=True, help_text='W procentach (%)', null=True, verbose_name='Promocja'),
        ),
    ]
