# Generated by Django 3.0.8 on 2021-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_auto_20210908_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='limit_per_two_weeks',
            field=models.CharField(default='2100 km', max_length=10, verbose_name='Limit 2 tygodnie'),
        ),
        migrations.AddField(
            model_name='car',
            name='limit_per_week',
            field=models.CharField(default='1400 km', max_length=10, verbose_name='Limit tygodniowo'),
        ),
    ]
