# Generated by Django 3.0.8 on 2021-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_auto_20210913_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentperiod',
            name='limit',
            field=models.IntegerField(default=200, verbose_name='Limit'),
        ),
    ]
