# Generated by Django 3.0.8 on 2021-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_carrentperiod_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentperiod',
            name='limit',
            field=models.IntegerField(default=200, verbose_name='Limit km dziennie'),
        ),
    ]
