# Generated by Django 3.0.8 on 2021-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_auto_20210913_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='non_working_hours',
            field=models.IntegerField(default=99, help_text='Cena', verbose_name='Wynajem / zwrot auta poza godzinami pracy biura'),
        ),
    ]
