# Generated by Django 3.0.8 on 2021-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_car_non_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentperiod',
            name='period_from',
            field=models.IntegerField(default=0, verbose_name='Od'),
        ),
        migrations.AddField(
            model_name='rentperiod',
            name='period_to',
            field=models.IntegerField(default=0, verbose_name='Do'),
        ),
    ]
