# Generated by Django 3.0.8 on 2021-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_auto_20210930_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='Nie wyświetlać auto na strone'),
        ),
    ]
