# Generated by Django 3.0.8 on 2021-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_car_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='Nie wyświetlać auto na stronie'),
        ),
    ]
