# Generated by Django 3.0.8 on 2021-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_auto_20211125_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='car',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
    ]
